export type searchOptionsType = {
  bottom: boolean;
  serviceAmount: number;
  serviceGroupId: string;
  serviceId: string;
  serviceName: string;
  serviceUnit: string;
  serviceWorkHour: number;
  sort: string;
  sortname: string;
  sortorder: string;
  top: boolean;
};
export type goodsSearchOptionsType = {
  goodsBrand: string;
  goodsClassOne: string;
  goodsClassOneName: string;
  goodsClassThree: string;
  goodsClassThreeName: string;
  goodsClassTwo: string;
  goodsClassTwoName: string;
  goodsCode: string;
  goodsImage: string;
  goodsName: string;
  goodsNickName: string;
  goodsPositionNumber: string;
  goodsStandard: string;
  goodsType: string;
  goodsUnit: string;
  goodsWarningInventory: boolean;
  goodsWarrantyPeriod: string;
  storeGoodsCostPrice: string;
  storeGoodsId: string;
  storeGoodsInventory: number;
  storeGoodsMaintenanceType: number;
  storeGoodsSalePrice: string;
  storeGoodsTotalSales: number;
  top: boolean;
};
export type carListType = {
  bottom?: boolean;
  carEngineCode: string;
  carId: string;
  carLastMaintenanceMileage: string;
  carMileageName: string;
  carModelsId: string;
  carModelsName: string;
  carModelsNameTwo: string;
  carName: string;
  carPlateNumber: string;
  driverUserPhone: string;
  relId: string;
  remark: string;
  storeId: string;
  top?: boolean;
  totalOrderNumber: number;
};
