// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    KlAutocomplete: typeof import('./components/kl-autocomplete/src/kl-autocomplete.vue')['default']
    KlCustomTable: typeof import('./components/kl-custom-table/src/kl-custom-table.vue')['default']
    KlExportDialog: typeof import('./components/kl-export-dialog/src/kl-export-dialog.vue')['default']
    KlImgPopover: typeof import('./components/kl-img-popover/src/kl-img-popover.vue')['default']
    KlTableHeader: typeof import('./components/kl-table-header/src/kl-table-header.vue')['default']
    KlTopBar: typeof import('./components/kl-top-bar/src/kl-top-bar.vue')['default']
  }
}

export { }
