export type tableDataType = {
  goodsBrand: string;
  goodsClassOne: string;
  goodsClassOneName: string;
  goodsClassThree: string;
  goodsClassThreeName: string;
  goodsClassTwo: string;
  goodsClassTwoName: string;
  goodsCode: string;
  goodsImage: string;
  goodsName: string;
  goodsNickName: string;
  goodsStandard: string;
  goodsType: string;
  goodsUnit: string;
  goodsWarningInventory: number;
  goodsWarrantyPeriod: string;
  storeGoodsCostPrice: string;
  storeGoodsId: string;
  storeGoodsInventory: number;
  storeGoodsMaintenanceType: number;
  storeGoodsSalePrice: string;
};
